/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_1_ee.h"
#include "ErikaOS_1_ee_tracing.h"
#include "SEVEN_Select_aliases.h"
#include "SEVEN_Select.h"
#include "Pin_1DP_aliases.h"
#include "Pin_1DP.h"
#include "Pin_1G_aliases.h"
#include "Pin_1G.h"
#include "Pin_1F_aliases.h"
#include "Pin_1F.h"
#include "Pin_1E_aliases.h"
#include "Pin_1E.h"
#include "Pin_1D_aliases.h"
#include "Pin_1D.h"
#include "Pin_1C_aliases.h"
#include "Pin_1C.h"
#include "Pin_1B_aliases.h"
#include "Pin_1B.h"
#include "Pin_1A_aliases.h"
#include "Pin_1A.h"
#include "Seven_Segment_Register.h"
#include "BUTTON_2_aliases.h"
#include "BUTTON_2.h"
#include "BUTTON_1_aliases.h"
#include "BUTTON_1.h"
#include "RGB_Blue_aliases.h"
#include "RGB_Blue.h"
#include "RGB_Green_aliases.h"
#include "RGB_Green.h"
#include "isr_button.h"
#include "RGB_Red_aliases.h"
#include "RGB_Red.h"
#include "isr_UARTLOG_RX.h"
#include "Clock_PWM.h"
#include "PWM_Led_Yellow.h"
#include "PWM_Led_Green.h"
#include "PWM_Led_Red.h"
#include "Pin_Yellow_Led_aliases.h"
#include "Pin_Yellow_Led.h"
#include "Pin_Green_Led_aliases.h"
#include "Pin_Green_Led.h"
#include "Pin_Red_Led_aliases.h"
#include "Pin_Red_Led.h"
#include "UART_LOG.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

